redhat-beyond/ResuMe

Vagrantfile, setup.sh
-Adding Setup.sh file
-Changing the vagrantfile
In order to automate the setup including:
1. Installing the Pipenv.
2. Installing software dependencies.
3. Starting out the application.
Fixes #6
=> Setup.sh addition

.github/workflows/flake8.yml, Pipfile, Pipfile.lock
- Installing Flake8 to the Vagrant VM.
- Adding Flake8 as GitHub Action.
Issue: #5
=> Setting up Flake8

README.md
This is the first version of the README file.
This file include general description of the project, and a guide for how to get started. 
fix #7
=> Editing README.md file

CONTRIBUTING.md
Adding CONTRIBUTING.md file, which describes the process of contributing the ResuMe project.
fix #12
=> Adding CONTRIBUTING.md file.

.github/workflows/pytest.yml, Pipfile, Pipfile.lock, pytest.ini, tests/test_helloworld.py
- Adding pytest as dev dependency
- creating a dummy test that always pass
- Adding pytest as github action.
fix : #17
=> Adding pytest

setup.sh
Replacing nohup command with setsid command in setup.sh (as Barak recommended)
Dependent on #43 
fix #44
=> Replacing nohup command with setsid

.gitignore
-Adding .idea folder to gitignore for PyCharm files.
fix #63
=> Adding idea files to gitignore

users/migrations/0003_add_users_test.py
Adding profile profession to users test data.
fix #86
=> Adding profile profession test data

ResuMe/settings.py, posts/static/posts/about.css, posts/static/posts/feed.css, posts/templates/posts/feed.html, posts/tests/test_comment.py, posts/tests/test_posts_views.py, posts/tests/tests.py, posts/urls.py, posts/views.py, static/styles/main.css, tests/test_helloworld.py
- Adding PostListView class to views.
- Displaying Resumes on feed as an embedded PDF.
- Changing the X-FRAME-OPTIONS so that embedded pdf display is allowed and not blocked by the browser.
Dependant on #77  ( please merge #77 before)
fix #88
=> Displaying Posts on feed

Pipfile, Pipfile.lock, ResuMe/settings.py, users/forms.py, users/models.py, users/templates/users/edit-profile.html, users/templates/users/profile.html, users/test_views.py, users/urls.py, users/views.py
- Create profile.html.
- Create edit_profile.html.
- allow users to update their settings using POST method.
- allow users add a new profile picture/ bio/ profession.
- Redirecting from profile.html to edit_profile.html when a user wants to edit his profile
- resize profile pic image when it is uploaded.
- install django-crispy-forms.
Dependant on #77 
fix #68
fix  #69 
fix #91
=> Create profile page and edit_profile page

posts/templates/posts/post_detail.html, posts/tests/conftest.py, posts/tests/test_posts.py, posts/tests/test_posts_views.py, posts/urls.py, posts/views.py
- Adding PostDetailView class to the views.
- Adding post_detail.html.
- Adding tests for the post detail's view.
- Adding Conftest.py for posts-tests fixtures.
fix #93
=> Adding Post detail view

ResuMe/settings.py, ResuMe/urls.py, direct_message/views.py, posts/views.py, templates/base.html, users/templates/users/login.html, users/test_users_views.py, users/test_views.py, users/urls.py
- Changing paths so to login/logout paths would be `localhost:8000/login` instead
of `localhost:8000/users/login`
- Updating the base template accordingly.
- Creating basic login page form.
- Adding login tests
fix #83
=> Setup login

posts/models.py, posts/static/posts/forms.css, posts/templates/posts/feed.html, posts/templates/posts/post_detail.html, posts/templates/posts/resume_form.html, posts/tests/conftest.py, posts/tests/test_posts.py, posts/tests/test_posts_views.py, posts/urls.py, posts/views.py, static/styles/main.css, templates/base.html
- Adding CreateResumeView class.
- Adding resume creation form html.
- Adding forms css.
- Adding tests to the create resume views.
- Adding create new post button to side bar.
fix #95 
Dependant on #94
=> Adding create Resume view

posts/urls.py, posts/views.py, tests/posts_tests/test_posts_views.py
- Adding UpdateResumeView class.
- Adding tests for update resume posts
fix #97
=> Adding update a Resume View

posts/models.py, posts/static/posts/feed.css, posts/templates/posts/comment_form.html, posts/templates/posts/feed.html, posts/templates/posts/post_detail.html, posts/urls.py, posts/views.py, static/styles/main.css, tests/conftest.py, tests/posts_tests/test_posts_views.py
- Adding comments to each post in feed view and detail view
- Adding `comment-create` view
- Adding tests
- Changing URL name from `posts-detail` to `post-detail`
Depending on #94 
fix #101
=> Adding comments view

ResuMe/urls.py, direct_message/urls.py, templates/base.html, tests/users_tests/test_users_views.py
- Delete direct-message url
- Delete direct-message from templates/base
fix #120
=> Delete direct-message from UI

users/migrations/0003_add_users_test.py
Changing user's passwords to be less complex passwords.
The new password is a firstname1234, for example 'yuli1234' .
fix #134 
* Don’t forget to delete db and run : pipenv python mange.py migrate after this pr will be merged.
=> Changing user's password

posts/models.py, posts/static/posts/rating.css, posts/templates/posts/feed.html, posts/templates/posts/post_detail.html, posts/templates/posts/rating_form.html, posts/templates/posts/rating_view.html, posts/urls.py, posts/views.py, tests/conftest.py, tests/posts_tests/test_posts.py, tests/posts_tests/test_ratings.py
- Adding Create rating form using Django's generic CreateView
- Creating a create Rating template
- Adding a button to create a rating in the feed and post view
- Adding validations for users to create only one Rating per resume
- Adding rating view show ratings in feed and post page
- Adding rating view tests
fix #132
=> Rating view

tests/posts_tests/test_posts_views.py
- adding a template check for posts views tests
- adding a non-existing post view test
- changing posts views tests to be more meaningful
fix #124
=> Fixing posts tests

ResuMe/urls.py, direct_message/static/direct_message/forms.css, direct_message/static/direct_message/message.css, direct_message/templates/direct_message/direct_message.html, direct_message/templates/direct_message/home.html, direct_message/templates/direct_message/main_messages.html, direct_message/templates/direct_message/message_form.html, direct_message/urls.py, direct_message/views.py, templates/base.html, tests/conftest.py, tests/direct_message_tests/test_view.py
- Adding direct_message_list view and direct_message_create view
- Adding main_messages, message_form and direct_message html files
- Adding direct button on base.html
- Adding direct_message_view tests
fix #137
=> Adding direct_message views

posts/static/posts/feed.css, users/templates/users/profile.html, users/templates/users/profile_details.html
- Added the 3 dots menu to the posts that are displayed in each profile.
- Adjusted the position of the comment and rate buttons so they won't overflow the comment section size.
fix #139 
co-authored with: @OmerCS8
=> Fixed minor UI bugs
